apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-jenkins-service
  labels:
    app: my-jenkins
spec:
  selector:
    app: my-jenkins
  type: NodePort
  ports: 
   - protocol: TCP
     port: 22
     name: sshlogin
     nodePort: 30122
   - protocol: TCP
     port: 8080
     name: jenkins
     nodePort: 30180
   - protocol: TCP
     port: 3000
     name: nodestandart
     nodePort: 30100
